import React, { useState, useEffect, useRef } from 'react';
import { PRESETS } from './presets';
import { PresetExample, AnnotationResponse, TraceStep } from './types';
import { Header } from './components/Header';
import { CodeViewer } from './components/CodeViewer';
import { TraceControls } from './components/TraceControls';
import { StepNotesCard } from './components/StepNotesCard';
import { VariableInspector } from './components/VariableInspector';
import { OutputTerminal } from './components/OutputTerminal';
import { AnnotationJsonView } from './components/AnnotationJsonView';
import { CustomTraceModal } from './components/CustomTraceModal';
import { Sparkles, AlertCircle, CheckCircle2 } from 'lucide-react';

export default function App() {
  const [activePresetId, setActivePresetId] = useState<string>(PRESETS[0].id);
  const [sourceCode, setSourceCode] = useState<string>(PRESETS[0].sourceCode);
  const [language, setLanguage] = useState<string>(PRESETS[0].language);
  const [trace, setTrace] = useState<TraceStep[]>(PRESETS[0].trace);
  const [annotations, setAnnotations] = useState<AnnotationResponse>(
    PRESETS[0].cachedAnnotations || { lines: [], variables: [], step_notes: [] }
  );

  const [currentStepIndex, setCurrentStepIndex] = useState<number>(0);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [playbackSpeed, setPlaybackSpeed] = useState<number>(1);
  const [activeTab, setActiveTab] = useState<'visualizer' | 'json'>('visualizer');
  const [isAnnotating, setIsAnnotating] = useState<boolean>(false);
  const [annotationSource, setAnnotationSource] = useState<'gemini' | 'cached' | 'fallback'>('cached');
  const [isCustomModalOpen, setIsCustomModalOpen] = useState<boolean>(false);
  const [notification, setNotification] = useState<{ message: string; type: 'success' | 'info' | 'error' } | null>(null);

  // Playback timer effect
  const playTimerRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    if (isPlaying) {
      const intervalMs = Math.round(1000 / playbackSpeed);
      playTimerRef.current = setInterval(() => {
        setCurrentStepIndex((prev) => {
          if (prev >= trace.length - 1) {
            setIsPlaying(false);
            return prev;
          }
          return prev + 1;
        });
      }, intervalMs);
    } else {
      if (playTimerRef.current) {
        clearInterval(playTimerRef.current);
      }
    }
    return () => {
      if (playTimerRef.current) {
        clearInterval(playTimerRef.current);
      }
    };
  }, [isPlaying, playbackSpeed, trace.length]);

  // Preset switching
  const handleSelectPreset = (presetId: string) => {
    if (presetId === 'custom') {
      setIsCustomModalOpen(true);
      return;
    }
    const found = PRESETS.find((p) => p.id === presetId);
    if (!found) return;

    setActivePresetId(found.id);
    setSourceCode(found.sourceCode);
    setLanguage(found.language);
    setTrace(found.trace);
    setCurrentStepIndex(0);
    setIsPlaying(false);
    if (found.cachedAnnotations) {
      setAnnotations(found.cachedAnnotations);
      setAnnotationSource('cached');
    } else {
      setAnnotations({ lines: [], variables: [], step_notes: [] });
    }
    showToast(`Loaded "${found.title}" preset.`, 'info');
  };

  // Run AI Annotation Engine via /api/annotate
  const handleAnnotateWithAi = async () => {
    setIsAnnotating(true);
    showToast('Annotation engine processing code & trace...', 'info');

    try {
      const res = await fetch('/api/annotate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sourceCode,
          language,
          trace,
        }),
      });

      if (!res.ok) {
        throw new Error(`Server returned status ${res.status}`);
      }

      const result = await res.json();
      if (result.data) {
        setAnnotations(result.data);
        setAnnotationSource(result.source || 'gemini');
        showToast(
          result.source === 'gemini'
            ? 'Annotations generated by Gemini API.'
            : 'Annotations generated via heuristic analyzer.',
          'success'
        );
      }
    } catch (err: any) {
      console.error('Annotation failed:', err);
      showToast('Annotation request failed. Check server logs.', 'error');
    } finally {
      setIsAnnotating(false);
    }
  };

  // Custom code & trace submission
  const handleCustomSubmit = (code: string, lang: string, newTrace: TraceStep[]) => {
    setActivePresetId('custom');
    setSourceCode(code);
    setLanguage(lang);
    setTrace(newTrace);
    setCurrentStepIndex(0);
    setIsPlaying(false);
    showToast('Custom code and trace loaded. Requesting AI annotations...', 'info');

    // Automatically trigger annotation
    setIsAnnotating(true);
    fetch('/api/annotate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sourceCode: code,
        language: lang,
        trace: newTrace,
      }),
    })
      .then((r) => r.json())
      .then((data) => {
        if (data.data) {
          setAnnotations(data.data);
          setAnnotationSource(data.source || 'gemini');
          showToast('Annotations ready for custom trace.', 'success');
        }
      })
      .catch((err) => {
        console.error(err);
        showToast('Annotation request failed.', 'error');
      })
      .finally(() => {
        setIsAnnotating(false);
      });
  };

  const showToast = (message: string, type: 'success' | 'info' | 'error') => {
    setNotification({ message, type });
    setTimeout(() => {
      setNotification((curr) => (curr?.message === message ? null : curr));
    }, 4000);
  };

  const currentStep = trace[currentStepIndex] || null;
  const previousStep = currentStepIndex > 0 ? trace[currentStepIndex - 1] : null;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-indigo-900 selection:text-indigo-200">
      
      {/* App Header */}
      <Header
        presets={PRESETS}
        activePresetId={activePresetId}
        onSelectPreset={handleSelectPreset}
        onOpenCustomModal={() => setIsCustomModalOpen(true)}
        onAnnotateWithAi={handleAnnotateWithAi}
        isAnnotating={isAnnotating}
        activeTab={activeTab}
        onTabChange={setActiveTab}
        annotationSource={annotationSource}
      />

      {/* Notification Toast */}
      {notification && (
        <div className="fixed bottom-5 right-5 z-50 transition-all">
          <div
            className={`flex items-center gap-2 px-4 py-2.5 rounded-xl shadow-xl border text-xs font-medium ${
              notification.type === 'success'
                ? 'bg-slate-900 text-slate-100 border-slate-700'
                : notification.type === 'error'
                ? 'bg-rose-950 text-rose-200 border-rose-800'
                : 'bg-slate-900 text-slate-100 border-slate-700 shadow-lg'
            }`}
          >
            {notification.type === 'success' && <CheckCircle2 className="w-4 h-4 text-emerald-400" />}
            {notification.type === 'error' && <AlertCircle className="w-4 h-4 text-rose-400" />}
            {notification.type === 'info' && <Sparkles className="w-4 h-4 text-indigo-400" />}
            <span>{notification.message}</span>
          </div>
        </div>
      )}

      {/* Main Content Area */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6">
        {activeTab === 'visualizer' ? (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 items-start">
            
            {/* Left Column (7 cols): Annotated Source Code Viewer */}
            <div className="lg:col-span-7 h-[calc(100vh-140px)] min-h-[550px]">
              <CodeViewer
                sourceCode={sourceCode}
                language={language}
                currentStep={currentStep}
                annotations={annotations.lines}
                onSelectLineStep={(stepIdx) => setCurrentStepIndex(stepIdx)}
                allSteps={trace}
              />
            </div>

            {/* Right Column (5 cols): Controls, Step Notes, Variables, Output */}
            <div className="lg:col-span-5 flex flex-col gap-4">
              
              {/* Stepper Controls & Scrubber */}
              <TraceControls
                currentStepIndex={currentStepIndex}
                totalSteps={trace.length}
                onStepChange={(idx) => setCurrentStepIndex(idx)}
                isPlaying={isPlaying}
                onTogglePlay={() => setIsPlaying(!isPlaying)}
                playbackSpeed={playbackSpeed}
                onChangeSpeed={setPlaybackSpeed}
                currentStep={currentStep}
              />

              {/* Notable Event / Step Note Card */}
              <StepNotesCard
                currentStep={currentStep}
                currentStepIndex={currentStepIndex}
                stepNotes={annotations.step_notes}
                allSteps={trace}
                onJumpToStep={(stepIdx) => setCurrentStepIndex(stepIdx)}
              />

              {/* Variables Inspector & Global Program Roles */}
              <VariableInspector
                currentStep={currentStep}
                previousStep={previousStep}
                variableRoles={annotations.variables}
                allSteps={trace}
                onSelectStep={(sIdx) => setCurrentStepIndex(sIdx)}
              />

              {/* Cumulative Standard Output */}
              <OutputTerminal output={currentStep?.output || ''} />

            </div>

          </div>
        ) : (
          /* JSON Schema Output Tab */
          <AnnotationJsonView
            annotations={annotations}
            sourceCode={sourceCode}
            trace={trace}
            annotationSource={annotationSource}
          />
        )}
      </main>

      {/* Status Footer */}
      <footer className="h-10 bg-slate-900 border-t border-slate-800 flex items-center px-4 sm:px-6 shrink-0 justify-between text-xs text-slate-400">
        <div className="flex items-center space-x-2">
          <span className="font-semibold text-slate-200">CodeTrace AI</span>
          <span className="text-slate-600">•</span>
          <span className="hidden sm:inline text-slate-400">Ground-truth Execution Trace & Annotation Engine</span>
        </div>
        <div className="text-[11px] text-slate-400">
          Trace Verified: <span className="text-emerald-400 font-bold">SANDBOX SECURE</span>
        </div>
      </footer>

      {/* Custom Trace Modal */}
      <CustomTraceModal
        isOpen={isCustomModalOpen}
        onClose={() => setIsCustomModalOpen(false)}
        onSubmit={handleCustomSubmit}
        initialCode={sourceCode}
        initialLanguage={language}
        initialTrace={trace}
      />

    </div>
  );
}
